### ISSUE TITLE
For everyone: Add Login with GitHub Feature to our sample Firebase app

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/pair-partners#40]
***Moved to https://github.com/LearnTeachCode/pair-partners/milestone/3***

**Comment by kammitama5** [comment]
Github authentication with Firebase: https://firebase.google.com/docs/auth/web/github-auth

**Comment by LearningNerd** [comment]
Funny comic on CORS via @remarks  ![](https://pbs.twimg.com/media/C2qrQlZWQAAHmGL.jpg)

(I think this is why we need to create a local server, to give GitHub an acceptable URL that it can play nice with when we let users login/authenticate using GitHub!)
